version: "3.0"

services:

  app:
    build: .
    container_name: api
    volumes:
    - ./src:/app
    - ./data:/data
    ports:
    - "8000:8000"
    entrypoint: ["uvicorn","app:app","--host","0.0.0.0","--port","8000"]
    restart: always   
